from django.core.files.uploadedfile import SimpleUploadedFile
from django.contrib.auth import get_user_model
from rest_framework.test import APITestCase
from rest_framework import status
from rest_framework_simplejwt.tokens import AccessToken
from accounts.models import School, Student, Teacher
from assessments.models import StudentAssessment, AssessmentModel

User = get_user_model()

class ProfileImageUploadTests(APITestCase):

    def setUp(self):
        # Create an authenticated user
        self.user = User.objects.create_user(
            email='testuser@amlos.com',
            username='testuser',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.token = str(AccessToken.for_user(self.user))
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.token}')

    def test_upload_image_successfully(self):
        # Create a mock image file
        mock_image = SimpleUploadedFile(
            name='profile.png',
            content=b'mock_image_binary_content',
            content_type='image/png'
        )

        response = self.client.post(
            '/api/auth/upload-image',
            {'image': mock_image},
            format='multipart'
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data['success'])
        self.assertIn('url', response.data['data'])
        self.assertIn('path', response.data['data'])
        self.assertTrue(response.data['data']['path'].startswith('profile_images/'))

    def test_upload_no_file_fails(self):
        response = self.client.post(
            '/api/auth/upload-image',
            {},
            format='multipart'
        )

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertFalse(response.data['success'])
        self.assertEqual(response.data['message'], "No image or file provided. Use key 'image' or 'file'.")


class ProfileImageAccountIntegrationTests(APITestCase):

    def setUp(self):
        # Create ADMIN user
        self.admin_user = User.objects.create_user(
            email='admin@amlos.com',
            username='admin',
            password='password123',
            role=User.Role.ADMIN
        )
        # Create SCHOOL user
        self.school_user = User.objects.create_user(
            email='school@amlos.com',
            username='school',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.school_profile = School.objects.create(
            user=self.school_user,
            school_name="Test School",
            registration_number="REG-MAIN",
            address="123 Main St",
            principal_name="Principal Main"
        )

        self.admin_token = str(AccessToken.for_user(self.admin_user))
        self.school_token = str(AccessToken.for_user(self.school_user))

    def test_create_school_with_profile_image(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.admin_token}')
        payload = {
            "username": "newschool@amlos.com",
            "password": "password123",
            "email": "newschool@amlos.com",
            "school_name": "New School",
            "registration_number": "REG-NEW",
            "address": "456 Side St",
            "principal_name": "Dr. New Principal",
            "profile_image": "https://s3.amazonaws.com/amlos/profile_images/school.png"
        }
        response = self.client.post('/api/auth/school/create', payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['data']['school']['profile_image'], "https://s3.amazonaws.com/amlos/profile_images/school.png")

        # Verify in DB
        created_user = User.objects.get(email="newschool@amlos.com")
        self.assertEqual(created_user.profile_image, "https://s3.amazonaws.com/amlos/profile_images/school.png")

    def test_create_school_autogenerates_registration_number_and_lists_created_at(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.admin_token}')
        
        # 1. Create school without registration_number but with phone
        payload = {
            "username": "newschool_auto@amlos.com",
            "password": "password123",
            "email": "newschool_auto@amlos.com",
            "school_name": "Autogen School",
            "address": "789 Auto St",
            "principal_name": "Principal Auto",
            "phone": "+1234567890"
        }
        response = self.client.post('/api/auth/school/create', payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        
        # Verify it autogenerated a registration number and saved the phone number
        reg_num = response.data['data']['school']['registration_number']
        self.assertTrue(reg_num.startswith("REG-"))
        self.assertEqual(len(reg_num), 12) # REG- (4 chars) + 8 chars = 12
        self.assertEqual(response.data['data']['school']['phone'], "+1234567890")

        # 2. Get all schools and verify created_at & phone are present in the response
        list_response = self.client.get('/api/auth/schools')
        self.assertEqual(list_response.status_code, status.HTTP_200_OK)
        
        results = list_response.data['data']['results']
        # Find the school we just created
        matched = [s for s in results if s['school_name'] == "Autogen School"]
        self.assertEqual(len(matched), 1)
        self.assertIn('created_at', matched[0])
        self.assertIsNotNone(matched[0]['created_at'])
        self.assertEqual(matched[0]['registration_number'], reg_num)
        self.assertEqual(matched[0]['phone'], "+1234567890")

    def test_create_student_with_profile_image(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        payload = {
            "username": "newstudent@amlos.com",
            "password": "password123",
            "email": "newstudent@amlos.com",
            "first_name": "John",
            "last_name": "Doe",
            "roll_number": "ROLL-STUD-1",
            "grade": "Grade 9",
            "profile_image": "https://s3.amazonaws.com/amlos/profile_images/student.png"
        }
        response = self.client.post('/api/auth/students/create', payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['data']['student']['profile_image'], "https://s3.amazonaws.com/amlos/profile_images/student.png")

        # Verify in DB
        created_user = User.objects.get(email="newstudent@amlos.com")
        self.assertEqual(created_user.profile_image, "https://s3.amazonaws.com/amlos/profile_images/student.png")

    def test_create_teacher_with_profile_image(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        payload = {
            "username": "newteacher@amlos.com",
            "password": "password123",
            "email": "newteacher@amlos.com",
            "first_name": "Jane",
            "last_name": "Smith",
            "subject": "Mathematics",
            "qualification": "Master of Education",
            "profile_image": "https://s3.amazonaws.com/amlos/profile_images/teacher.png"
        }
        response = self.client.post('/api/auth/create-teacher', payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['data']['teacher']['profile_image'], "https://s3.amazonaws.com/amlos/profile_images/teacher.png")

        # Verify in DB
        created_user = User.objects.get(email="newteacher@amlos.com")
        self.assertEqual(created_user.profile_image, "https://s3.amazonaws.com/amlos/profile_images/teacher.png")


class TeacherStudentAssignmentTests(APITestCase):

    def setUp(self):
        # Create School
        self.school_user = User.objects.create_user(
            email='school@amlos.com',
            username='school',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.school_profile = School.objects.create(
            user=self.school_user,
            school_name="Test School",
            registration_number="REG-MAIN",
            address="123 Main St",
            principal_name="Principal Main"
        )

        # Create Teacher
        self.teacher_user = User.objects.create_user(
            email='teacher@amlos.com',
            username='teacher',
            password='password123',
            role=User.Role.TEACHER
        )
        self.teacher_profile = Teacher.objects.create(
            user=self.teacher_user,
            school=self.school_profile,
            subject="Maths",
            qualification="B.Sc"
        )

        # Create Student 1 (Assigned)
        self.student_user1 = User.objects.create_user(
            email='student1@amlos.com',
            username='student1',
            password='password123',
            role=User.Role.STUDENT
        )
        self.student_profile1 = Student.objects.create(
            user=self.student_user1,
            school=self.school_profile,
            roll_number="S1",
            grade="Grade 10"
        )

        # Create Student 2 (Unassigned)
        self.student_user2 = User.objects.create_user(
            email='student2@amlos.com',
            username='student2',
            password='password123',
            role=User.Role.STUDENT
        )
        self.student_profile2 = Student.objects.create(
            user=self.student_user2,
            school=self.school_profile,
            roll_number="S2",
            grade="Grade 10"
        )

        # Create Subject
        from curriculum.models import Subject
        self.subject = Subject.objects.create(
            name="Mathematics",
            description="Math Description",
            grade="Grade 10"
        )

        # Create Assessment
        self.assessment = AssessmentModel.objects.create(
            title="Algebra Final",
            assessment_type=AssessmentModel.AssessmentType.CHAPTER_WISE,
            grade="Grade 10",
            subject=self.subject,
            total_questions=5
        )

        # Create submissions for both students
        self.submission1 = StudentAssessment.objects.create(
            student=self.student_user1,
            assessment_model=self.assessment,
            is_completed=True,
            score=0,
            total_marks=100
        )
        self.submission2 = StudentAssessment.objects.create(
            student=self.student_user2,
            assessment_model=self.assessment,
            is_completed=True,
            score=0,
            total_marks=100
        )

        self.school_token = str(AccessToken.for_user(self.school_user))
        self.teacher_token = str(AccessToken.for_user(self.teacher_user))

    def test_school_assigns_students_to_teacher(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        url = f'/api/auth/teachers/{self.teacher_profile.id}/assign-students'
        
        # Test assigning Student 1
        payload = {"student_ids": [self.student_profile1.id]}
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data['success'])
        self.assertEqual(response.data['data']['assigned_student_ids'], [self.student_profile1.id])

        # Test listing teacher profile shows assigned students
        get_url = '/api/auth/teachers'
        response_list = self.client.get(get_url)
        self.assertEqual(response_list.status_code, status.HTTP_200_OK)
        teachers = response_list.data['data']
        matched = [t for t in teachers if t['id'] == self.teacher_profile.id]
        self.assertEqual(len(matched), 1)
        self.assertEqual(len(matched[0]['assigned_students']), 1)
        self.assertEqual(matched[0]['assigned_students'][0]['id'], self.student_profile1.id)

    def test_teacher_submission_visibility_and_grading(self):
        # First assign Student 1 to Teacher
        self.teacher_profile.students.add(self.student_profile1)

        # Authenticate as Teacher
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.teacher_token}')

        # 1. Fetch submissions. The teacher should only see submission 1 (assigned student)
        submissions_url = '/api/assessments/submissions'
        response = self.client.get(submissions_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        results = response.data['data']['results']
        # The teacher should only see submission1 (Student 1) and NOT submission2
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]['id'], self.submission1.id)

        # 2. Grade Submission 1 (Should succeed)
        grade_url1 = f'/api/assessments/submissions/{self.submission1.id}/grade'
        grade_payload = {"score": 85}
        response_grade1 = self.client.patch(grade_url1, grade_payload, format='json')
        self.assertEqual(response_grade1.status_code, status.HTTP_200_OK)
        self.assertTrue(response_grade1.data['success'])
        self.assertEqual(response_grade1.data['data']['score'], 85)

        # 3. Grade Submission 2 (Should fail with 403 Forbidden since Student 2 is not assigned)
        grade_url2 = f'/api/assessments/submissions/{self.submission2.id}/grade'
        response_grade2 = self.client.patch(grade_url2, grade_payload, format='json')
        self.assertEqual(response_grade2.status_code, status.HTTP_403_FORBIDDEN)
        self.assertFalse(response_grade2.data['success'])
        self.assertEqual(response_grade2.data['message'], "You are not authorized to grade this student's submission.")


class ResetPasswordByRoleTests(APITestCase):

    def setUp(self):
        # Create Admin
        self.admin_user = User.objects.create_user(
            email='admin@amlos.com',
            username='admin',
            password='password123',
            role=User.Role.ADMIN
        )

        # Create School
        self.school_user = User.objects.create_user(
            email='school@amlos.com',
            username='school',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.school_profile = School.objects.create(
            user=self.school_user,
            school_name="Main School",
            registration_number="REG-MAIN-PW",
            address="123 Road",
            principal_name="Principal Main"
        )

        # Create Teacher belonging to school
        self.teacher_user = User.objects.create_user(
            email='teacher@amlos.com',
            username='teacher',
            password='password123',
            role=User.Role.TEACHER
        )
        self.teacher_profile = Teacher.objects.create(
            user=self.teacher_user,
            school=self.school_profile,
            subject="Science",
            qualification="M.Sc"
        )

        # Create Student belonging to school
        self.student_user = User.objects.create_user(
            email='student@amlos.com',
            username='student',
            password='password123',
            role=User.Role.STUDENT
        )
        self.student_profile = Student.objects.create(
            user=self.student_user,
            school=self.school_profile,
            roll_number="STUD-PW",
            grade="Grade 10"
        )

        # Create another school and a teacher from that school (to test cross-school boundaries)
        self.other_school_user = User.objects.create_user(
            email='school2@amlos.com',
            username='school2',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.other_school_profile = School.objects.create(
            user=self.other_school_user,
            school_name="Other School",
            registration_number="REG-OTHER-PW",
            address="456 Road",
            principal_name="Principal Other"
        )
        self.other_teacher_user = User.objects.create_user(
            email='otherteacher@amlos.com',
            username='otherteacher',
            password='password123',
            role=User.Role.TEACHER
        )
        self.other_teacher_profile = Teacher.objects.create(
            user=self.other_teacher_user,
            school=self.other_school_profile,
            subject="History",
            qualification="B.A"
        )

        # Access Tokens
        self.admin_token = str(AccessToken.for_user(self.admin_user))
        self.school_token = str(AccessToken.for_user(self.school_user))
        self.teacher_token = str(AccessToken.for_user(self.teacher_user))

    def test_admin_resets_school_password_success(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.admin_token}')
        url = '/api/auth/reset-password-by-role'
        payload = {
            "user_id": self.school_user.id,
            "new_password": "new_school_password_123",
            "role": "SCHOOL"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data['success'])
        self.assertEqual(response.data['message'], "Password for SCHOOL user reset successfully.")

        # Try to authenticate/login with new password
        login_response = self.client.post('/api/auth/login', {
            "email": "school@amlos.com",
            "password": "new_school_password_123"
        }, format='json')
        self.assertEqual(login_response.status_code, status.HTTP_200_OK)

    def test_school_resets_school_password_forbidden(self):
        # A School trying to reset their own or another school's password via this endpoint should be forbidden
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        url = '/api/auth/reset-password-by-role'
        payload = {
            "user_id": self.school_user.id,
            "new_password": "unauthorized_reset_123",
            "role": "SCHOOL"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_school_resets_teacher_password_success(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        url = '/api/auth/reset-password-by-role'
        payload = {
            "user_id": self.teacher_user.id,
            "new_password": "new_teacher_pass_123",
            "role": "TEACHER"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)

        # Authenticate with new password
        login_response = self.client.post('/api/auth/login', {
            "email": "teacher@amlos.com",
            "password": "new_teacher_pass_123"
        }, format='json')
        self.assertEqual(login_response.status_code, status.HTTP_200_OK)

    def test_school_resets_other_teacher_password_forbidden(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.school_token}')
        url = '/api/auth/reset-password-by-role'
        payload = {
            "user_id": self.other_teacher_user.id,
            "new_password": "unauthorized_teacher_pass",
            "role": "TEACHER"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
        self.assertFalse(response.data['success'])
        self.assertEqual(response.data['message'], "This teacher does not belong to your school.")

    def test_teacher_resets_password_forbidden(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.teacher_token}')
        url = '/api/auth/reset-password-by-role'
        payload = {
            "user_id": self.student_user.id,
            "new_password": "teacher_unauthorized",
            "role": "STUDENT"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)


from curriculum.models import Subject
from accounts.models import PaperCheckerProfile, PaperCheckerAssignment, Student, Teacher, School
from assessments.models import AssessmentModel, StudentAssessment

class PaperCheckerTests(APITestCase):

    def setUp(self):
        self.admin_user = User.objects.create_user(
            email='admin@amlos.com',
            username='admin',
            password='password123',
            role=User.Role.ADMIN
        )
        self.school_user = User.objects.create_user(
            email='school@amlos.com',
            username='school',
            password='password123',
            role=User.Role.SCHOOL
        )
        self.school = School.objects.create(
            user=self.school_user,
            school_name="Main School",
            registration_number="REG-MAIN",
            address="123 Road"
        )
        self.student_user = User.objects.create_user(
            email='student@amlos.com',
            username='student',
            password='password123',
            role=User.Role.STUDENT
        )
        self.student = Student.objects.create(
            user=self.student_user,
            school=self.school,
            roll_number="S1"
        )
        self.teacher_user = User.objects.create_user(
            email='teacher@amlos.com',
            username='teacher',
            password='password123',
            role=User.Role.TEACHER
        )
        self.teacher = Teacher.objects.create(
            user=self.teacher_user,
            school=self.school,
            subject="Mathematics"
        )
        self.teacher.students.add(self.student)
        
        self.subject = Subject.objects.create(
            name="Mathematics",
            description="Math Desc",
            grade="Grade 9"
        )
        self.assessment = AssessmentModel.objects.create(
            title="Algebra Assessment",
            assessment_type="CHAPTER_WISE",
            grade="Grade 9",
            subject=self.subject,
            total_questions=0
        )
        self.submission = StudentAssessment.objects.create(
            student=self.student_user,
            assessment_model=self.assessment,
            is_completed=True,
            score=0,
            total_marks=10
        )
        
        self.admin_token = str(AccessToken.for_user(self.admin_user))
        self.teacher_token = str(AccessToken.for_user(self.teacher_user))

    def test_create_and_assign_paper_checker(self):
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.admin_token}')
        
        # 1. Create Paper Checker
        url = '/api/auth/paper-checkers/create'
        payload = {
            "username": "checker@amlos.com",
            "password": "password123",
            "email": "checker@amlos.com"
        }
        response = self.client.post(url, payload, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        checker_id = response.data['data']['paper_checker']['id']
        
        # 1.5 List Paper Checkers and verify created checker is in response
        list_checkers_url = '/api/auth/paper-checkers'
        list_checkers_response = self.client.get(list_checkers_url)
        self.assertEqual(list_checkers_response.status_code, status.HTTP_200_OK)
        self.assertTrue(list_checkers_response.data['success'])
        checkers = list_checkers_response.data['data']
        self.assertEqual(len(checkers), 1)
        self.assertEqual(checkers[0]['id'], checker_id)
        self.assertEqual(checkers[0]['email'], "checker@amlos.com")
        
        # 2. Assign Subject and Student to Checker
        assign_url = f'/api/auth/paper-checkers/{checker_id}/assign'
        assign_payload = {
            "subject_id": self.subject.id,
            "student_ids": [self.student.id]
        }
        assign_response = self.client.post(assign_url, assign_payload, format='json')
        self.assertEqual(assign_response.status_code, status.HTTP_200_OK)
        self.assertEqual(assign_response.data['data']['student_ids'], [self.student.id])

        # 3. Test Teacher submissions listing excludes this submission
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.teacher_token}')
        sub_list_response = self.client.get('/api/assessments/submissions')
        self.assertEqual(sub_list_response.status_code, status.HTTP_200_OK)
        # Should be empty since student submission for this subject is routed to the paper checker
        self.assertEqual(len(sub_list_response.data['data']['results']), 0)

        # 4. Test Teacher grading is Forbidden
        grade_url = f'/api/assessments/submissions/{self.submission.id}/grade'
        grade_response = self.client.patch(grade_url, {"score": 8}, format='json')
        self.assertEqual(grade_response.status_code, status.HTTP_403_FORBIDDEN)

        # 5. Test Paper Checker submissions listing and grading
        checker_user = User.objects.get(email="checker@amlos.com")
        checker_token = str(AccessToken.for_user(checker_user))
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {checker_token}')
        
        checker_sub_list = self.client.get('/api/assessments/submissions')
        self.assertEqual(checker_sub_list.status_code, status.HTTP_200_OK)
        self.assertEqual(len(checker_sub_list.data['data']['results']), 1)
        self.assertEqual(checker_sub_list.data['data']['results'][0]['id'], self.submission.id)

        # Grade the paper as checker
        checker_grade = self.client.patch(grade_url, {"score": 9}, format='json')
        self.assertEqual(checker_grade.status_code, status.HTTP_200_OK)
        self.submission.refresh_from_db()
        self.assertEqual(self.submission.score, 9)

    def test_duplicate_username_validation(self):
        school_token = str(AccessToken.for_user(self.school_user))
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {school_token}')

        # 1. Attempt to create teacher with existing username (e.g. 'admin')
        teacher_url = '/api/auth/create-teacher'
        teacher_payload = {
            "username": "admin",
            "password": "password123",
            "email": "unique_teacher@amlos.com",
            "subject": "Mathematics"
        }
        teacher_response = self.client.post(teacher_url, teacher_payload, format='json')
        self.assertEqual(teacher_response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertFalse(teacher_response.data['success'])
        self.assertIn("Username already exists.", teacher_response.data['message'])

        # 2. Attempt to create student with existing username (e.g. 'admin')
        student_url = '/api/auth/students/create'
        student_payload = {
            "username": "admin",
            "password": "password123",
            "email": "unique_student@amlos.com",
            "roll_number": "S100",
            "grade": "Grade 9"
        }
        student_response = self.client.post(student_url, student_payload, format='json')
        self.assertEqual(student_response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertFalse(student_response.data['success'])
        self.assertIn("Username already exists.", student_response.data['message'])

    def test_checker_portion_assignment(self):
        # Update self.student to have Grade 9
        self.student.grade = "Grade 9"
        self.student.save()

        # Create another student in Grade 9
        student_user2 = User.objects.create_user(
            email='student2@amlos.com',
            username='student2',
            password='password123',
            role=User.Role.STUDENT
        )
        student2 = Student.objects.create(
            user=student_user2,
            school=self.school,
            roll_number="S2",
            grade="Grade 9"
        )
        
        # Create a paper checker
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.admin_token}')
        url = '/api/auth/paper-checkers/create'
        payload = {
            "username": "checker3@amlos.com",
            "password": "password123",
            "email": "checker3@amlos.com"
        }
        res = self.client.post(url, payload, format='json')
        checker_id = res.data['data']['paper_checker']['id']

        # 1. Assign portion "half" (1 out of 2 students)
        assign_url = f'/api/auth/paper-checkers/{checker_id}/assign'
        assign_payload = {
            "subject_id": self.subject.id,
            "portion": "half"
        }
        assign_response = self.client.post(assign_url, assign_payload, format='json')
        self.assertEqual(assign_response.status_code, status.HTTP_200_OK)
        # S1 has lower ID than S2, so it should assign S1
        self.assertEqual(len(assign_response.data['data']['student_ids']), 1)
        self.assertEqual(assign_response.data['data']['student_ids'][0], self.student.id)

        # 2. Assign portion "half" + custom student_ids (which should combine them)
        assign_payload = {
            "subject_id": self.subject.id,
            "portion": "half",
            "student_ids": [student2.id]
        }
        assign_response = self.client.post(assign_url, assign_payload, format='json')
        self.assertEqual(assign_response.status_code, status.HTTP_200_OK)
        # Should now assign both S1 (from portion) and S2 (from student_ids)
        self.assertEqual(len(assign_response.data['data']['student_ids']), 2)
        self.assertIn(self.student.id, assign_response.data['data']['student_ids'])
        self.assertIn(student2.id, assign_response.data['data']['student_ids'])


