from django.urls import path
from accounts.views import  *

urlpatterns = [
    path('admin/signup', AdminSignupView.as_view(), name='admin-signup'),
    path('login', LoginView.as_view()),
    path('school/create', CreateSchoolView.as_view()),
    path('students/create', CreateStudentView.as_view()),
    path('students', GetAllStudentsView.as_view()),
    path('students/<int:student_id>', UpdateStudentView.as_view()),
    path('students/<int:student_id>/delete', DeleteStudentView.as_view()),
    path('create-teacher', CreateTeacherView.as_view()),
    path('teachers', GetAllTeachersView.as_view()),
    path('teachers/<int:teacher_id>', UpdateTeacherView.as_view()),
    path('teachers/<int:teacher_id>/delete', DeleteTeacherView.as_view()),
    path('schools', GetAllSchoolsView.as_view()),
    path('schools/<int:school_id>/students', GetSchoolStudentsView.as_view()),
    path('schools/<int:school_id>/update', UpdateSchoolView.as_view()),
    path('schools/<int:school_id>/delete', DeleteSchoolView.as_view()),
    path('password-reset/request', RequestPasswordResetView.as_view(), name='password-reset-request'),
    path('password-reset/confirm', ConfirmPasswordResetView.as_view(), name='password-reset-confirm'),
    path('password-reset/redirect', PasswordResetRedirectView.as_view(), name='password-reset-redirect'),
    path('users', UserListSearchView.as_view()),
    path('users/<int:user_id>/role', UpdateUserRoleView.as_view()),
    path('upload-image', UploadProfileImageView.as_view(), name='upload-image'),
    path('teachers/<int:teacher_id>/assign-students', AssignStudentsToTeacherView.as_view(), name='assign-students-to-teacher'),
    path('reset-password-by-role', ResetUserPasswordByRoleView.as_view(), name='reset-password-by-role'),
    path('paper-checkers/create', CreatePaperCheckerView.as_view(), name='create-paper-checker'),
    path('paper-checkers/<int:checker_id>/assign', AssignSubjectStudentsToCheckerView.as_view(), name='assign-paper-checker'),
]