# Generated by Django 5.2.12 on 2026-06-18 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0005_slo_form_of_assessment_slo_google_drive_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=50)),
                ('cognitive_level', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=10, null=True)),
                ('short_explanation', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField()),
                ('answer_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('time_allowed_minutes', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'questions',
                'unique_together': {('subject', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('CHAPTER_WISE', 'Chapter-wise'), ('QUARTER', 'Quarter'), ('HALF', 'Half'), ('THIRD_QUARTER', 'Third Quarter'), ('FULL_BOOK', 'Full Book')], max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('cognitive_levels', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('total_questions', models.IntegerField()),
                ('mcq_count', models.IntegerField(default=0)),
                ('short_count', models.IntegerField(default=0)),
                ('long_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapters', models.ManyToManyField(related_name='assessments', to='curriculum.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum.subject')),
                ('questions', models.ManyToManyField(blank=True, related_name='assessments', to='assessments.question')),
            ],
            options={
                'db_table': 'assessment_models',
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessmentmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_assessments',
                'unique_together': {('student', 'assessment_model')},
            },
        ),
    ]
