# Generated by Django 5.2.12 on 2026-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assessment_submissions/'),
        ),
    ]
