# Generated by Django 5.2.12 on 2026-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_studentassessment_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodel',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes. Leave blank/null for no time limit.', null=True),
        ),
    ]
