# Generated by Django 5.2.12 on 2026-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentmodel_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodel',
            name='cognitive_level_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
