# Generated by Django 5.2.12 on 2026-07-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_examtype_assessmentmodel_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='question_bulk_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_bulk_uploads',
            },
        ),
    ]
