# Generated by Django 5.2.12 on 2026-04-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_subject_grade_alter_subject_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel'), ('CUSTOM', 'Custom')], default='PARALLEL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_limit_minutes', models.IntegerField(default=180)),
                ('custom_pattern', models.JSONField(blank=True, null=True)),
                ('subject_order', models.JSONField(blank=True, null=True)),
                ('total_slo_time', models.IntegerField(default=0)),
                ('total_available_time', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_plans',
            },
        ),
        migrations.CreateModel(
            name='StudyPlanSLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('order_in_day', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(max_length=200)),
                ('estimated_time', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_slos', to='study_plans.studyplan')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.slo')),
            ],
            options={
                'db_table': 'study_plan_slos',
                'ordering': ['scheduled_date', 'order_in_day'],
            },
        ),
    ]
