# Generated by Django 5.2.12 on 2026-04-07 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='daily_limit_minutes',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_completable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='last_recalculated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='max_study_time_daily',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='min_study_time_daily',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='studyplanslo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
