# Generated by Django 5.2.12 on 2026-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0002_remove_studyplan_daily_limit_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='last_recalculated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
