# Generated by Django 5.2.12 on 2026-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0003_alter_studyplan_last_recalculated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
