# Generated by Django 5.2.12 on 2026-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0005_studyplanslo_completed_at_dailytimespent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='skip_weekends',
            field=models.BooleanField(default=False),
        ),
    ]
