# Generated by Django 5.2.12 on 2026-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='study_time_daily',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='max_study_time_daily',
            field=models.IntegerField(default=120),
        ),
    ]
