# Generated by Django 5.2.12 on 2026-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
