# Generated by Django 5.2.12 on 2026-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role_financeprofile_hrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, help_text="S3 URL of the user's profile image", max_length=500, null=True),
        ),
    ]
