# Generated by Django 5.2.12 on 2026-07-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_school_phone'),
        ('curriculum', '0007_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SCHOOL', 'School'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('PAPER_CHECKER', 'Paper Checker')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PaperCheckerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_checker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_checker_profiles',
            },
        ),
        migrations.CreateModel(
            name='PaperCheckerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='paper_checker_assignments', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_checker_assignments', to='curriculum.subject')),
                ('paper_checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.papercheckerprofile')),
            ],
            options={
                'db_table': 'paper_checker_assignments',
                'unique_together': {('paper_checker', 'subject')},
            },
        ),
    ]
