# Generated by Django 5.2.12 on 2026-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('source', models.TextField(blank=True, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_urls',
            },
        ),
    ]
