# Generated by Django 5.2.12 on 2026-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='board_exam_date',
        ),
        migrations.AddField(
            model_name='subject',
            name='sheet_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
