# Generated by Django 5.2.12 on 2026-04-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_subject_board_exam_date_subject_sheet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sheet_url',
        ),
    ]
