# Generated by Django 5.2.12 on 2026-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_subject_grade_alter_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='form_of_assessment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slo',
            name='google_drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slo',
            name='google_site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slo',
            name='priority_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slo',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slo',
            name='slo_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slo',
            name='estimated_time',
            field=models.IntegerField(blank=True, help_text='Estimated time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='slo',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
