# Generated by Django 5.2.12 on 2026-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_slo_form_of_assessment_slo_google_drive_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('uploaded_file', models.FileField(upload_to='bulk_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'curriculum_bulk_uploads',
            },
        ),
    ]
